# Generated by Django 4.2 on 2023-04-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0004_task_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='team',
            field=models.ManyToManyField(related_name='members', through='project_management.Members', to='project_management.team'),
        ),
    ]
